# This file generates the GitHub Actions matrix.
---
include:
  - board: nice_nano_v2
    shield: ferris_rev02_left  # For the left (central) half; adjust if your shield name differs
  - board: nice_nano_v2
    shield: ferris_rev02_right  # For the right (peripheral) half; adjust if your shield name differs
